name: 'SalesDataMart'
version: '1.0.0'
config-version: 2

profile: 'SalesDataMart'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  SalesDataMart:
    +transient: false
    RAW:
      +materialized: table
      +schema: RAW
      +tags: raw
      +depends_on:
        - seed.customers
        - seed.sales
        - seed.stores
        - seed.time
    STAGE:
      +materialized: table
      +schema: STAGE
      +tags: stage

seeds:
  SalesDataMart:
    +schema: raw

vars:
  dbt_date:
    time_zone: 'Asia/Kolkata'
